### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-csharp-sdk#4]
Looks, like Travis CI is misconfigured, and Appveyor is not connected...

* [x] Travis - build for mono (fixed in #7)
* [x] AppVeyor (build for windows)
* [ ] search for online linting service
* [ ] tune linting integration

**Comment by maxkoryukov** [comment]
Travis: fixed in #7

**Comment by novapulsar** [comment]
http://www.bashy.io/ ?
