### ISSUE TITLE
Optimization fails when member_id is empty string

### ISSUE THREAD

**Issue by ventoshe** [route4me/route4me-csharp-sdk#8]
When passing an empty string in member_id property of RouteParameters, the response is as follows:
{
  "State": 0,
  "UserErrors": [
    "Internal error, please include following information when reporting this possible bug: Thu, 13 Apr 2017 15:06:00 -0400 / r4m-web3"
  ],
  "OptimizationId": null,
  "Routes": null,
  "Addresses": null
}

**Comment by Olman62** [comment]
It was an API issue (not SDK), but the bag was fixed years ago.
